Corrected mistakes
kurban1998/TestAppWithDatabase pull request #2
Opened 2021-10-03 11:11 UTC by kurban1998

2021-10-03 12:02 UTC, kurban1998 commented
Corrected mistakes

2021-10-06 11:22 UTC, prbll requested changes
Есть места, которые нужно поправить

2021-10-06 11:22 UTC, prbll commented on .gitignore
> +SkrugaDBUnitTest/SkrugaDBTest/bin/
Лучше добавить такие строки:
[Bb]in/
[Oo]bj/
Это будет применяться для всех бинарей во всех папках с учетом регистра

2021-10-06 11:22 UTC, prbll commented on .gitignore
> +#myignorefiles
Теперь нужно удалить все заигноренные файлы, которые остались в удаленном репозитории: https://stackoverflow.com/questions/7927230/remove-directory-from-remote-repository-after-adding-them-to-gitignore

2021-10-06 11:22 UTC, prbll commented on SkrugaDBUnitTest/CircleSquare.UnitTest/UnitTest1.cs
> +    public class CircleSquareUnitTest
Сами классы обычно называют в формате {ИмяТестируемогоКласса}{Tests}, то есть без слова Unit в этом случае

2021-10-06 11:22 UTC, prbll commented on SkrugaDBUnitTest/CircleSquare.UnitTest/UnitTest1.cs
> +            SkrugaDBTest.CircleSquare circle = new SkrugaDBTest.CircleSquare();
Создание экземпляра класса CirceSquare можно вынести в метод TestInitilialize, помеченный соответствующим аттрибутом: https://www.c-sharpcorner.com/UploadFile/dacca2/test-initialize-and-test-setup/
Этот метод будет вызывать перед каждым тестом и будет создавать экземпляр, не нужно будет делать это в каждом тесте

2021-10-06 11:22 UTC, prbll commented on SkrugaDBUnitTest/CircleSquare.UnitTest/UnitTest1.cs
> +            Assert.Equals(0, 0);
Почему actual не участвует в сравнении?

2021-10-06 11:22 UTC, prbll commented on SkrugaDBUnitTest/SkrugaDBTest/CircleSquare.cs
> +        public double AreaCircleSquare1(double radius)
Лучше назвать метод CalculateCircleArea

2021-10-06 11:22 UTC, prbll commented on SkrugaDBUnitTest/SkrugaDBTest/CircleSquare.cs
> +                return ArgumentOutOfRangeException;
Здесь нужно выбрасывать исключение: https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/exceptions/creating-and-throwing-exceptions

2021-10-06 11:22 UTC, prbll commented on SkrugaDBUnitTest/SkrugaDBTest/Program.cs
> +namespace CircleAreaCalculator
Нужно соответственно поменять имя проекта

2021-10-06 11:22 UTC, prbll commented on SkrugaDBUnitTest/SkrugaDBTest/CircleSquare.cs
> +    public class AreaCalculator
Нужно переименовать файл класса

2021-10-06 11:22 UTC, prbll commented on SkrugaDBUnitTest/SkrugaDBTest/Program.cs
> -                while (true)
Почему не добавил выход по кнопке просто?

2021-10-06 11:22 UTC, prbll commented on SkrugaDBUnitTest/SkrugaDBTest/CircleSquare.cs
> +                return ArgumentOutOfRangeException;
И соответственно тест поправить

2021-10-06 11:22 UTC, prbll commented on SkrugaDBUnitTest/SkrugaDBTest/Program.cs
>                          Console.WriteLine("Введите радиус круга");
Этот код собирается вообще? Здесь используется класс и метод, которые уже переименованы?
Никогда нельзя в удаленный репозиторий (remote) отправлять код, который не собирается

2021-10-26 08:30 UTC, merged